version: "3.7"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    env_file:
      - config.env

  kensurbot:
      build:
        context: https://github.com/KenHV/KensurBot.git#master
      depends_on:
        - db
      restart: always
      env_file:
        - config.env
